- name: 'Run the tests'
  hosts: localhost
  tasks:
    - name: Get a namespace
      ccamacho.automationhub.get_namespace:
        api_server: "https://galaxy.ansible.com"
        token: "thisisatoken"
        namespace: "kubeinitnonono" # this can be a namespace or a repo like ccamacho/kubeinit
